name: virtualEnvironmentScrapy
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi
  - attrs
  - automat
  - backcall
  - bcrypt
  - blas
  - bleach
  - ca-certificates
  - certifi
  - cffi
  - colorama
  - constantly
  - cryptography
  - cssselect
  - decorator
  - defusedxml
  - entrypoints
  - hyperlink
  - idna
  - importlib-metadata
  - importlib_metadata
  - incremental
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - itemadapter
  - itemloaders
  - jedi
  - jinja2
  - jmespath
  - jsonschema
  - jupyter_client
  - jupyter_core
  - libiconv
  - libsodium
  - libxml2
  - libxslt
  - lxml
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - markupsafe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msys2-conda-epoch
  - nbconvert
  - nbformat
  - notebook
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parsel
  - parso
  - pickleshare
  - pip
  - prometheus_client
  - prompt-toolkit
  - protego
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pydispatcher
  - pygments
  - pyhamcrest
  - pyopenssl
  - pyparsing
  - pyrsistent
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pywin32
  - pywinpty
  - pyzmq
  - queuelib
  - scrapy
  - send2trash
  - service_identity
  - setuptools
  - six
  - sqlite
  - terminado
  - testpath
  - tornado
  - traitlets
  - twisted
  - vc
  - vs2015_runtime
  - w3lib
  - wcwidth
  - webencodings
  - wheel
  - wincertstore
  - winpty
  - zeromq
  - zipp
  - zlib
  - zope
  - zope.interface
  - pip:
    - beautifulsoup4
    - chardet
    - et-xmlfile
    - jdcal
    - openpyxl
    - proxyscrape
    - requests
    - scrapy-proxy-pool
    - scrapy-rotating-proxies
    - scrapy-user-agents
    - soupsieve
    - typing
    - ua-parser
    - urllib3
    - user-agents
